name: Build and Push Docker Image (Dev)

on:
  push:
    branches:
      - dev-kubernetes

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}

      - name: Save image tag to file
        run: echo "ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}" > image.txt

      - name: Upload image tag as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-tag
          path: image.txt
