name: CI with Auto-Revert on Failure

on:
  push:  # ✅ Will trigger on ALL branches

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    continue-on-error: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate build failure
        run: |
          echo "Running build/tests..."
          exit 1  # ❌ Simulate failure (replace with real tests)

  revert:
    runs-on: ubuntu-latest
    name: Auto Revert Failed Commit
    needs: build
    if: failure()  # ✅ Only run if build fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Revert last commit
        run: |
          git revert --no-edit HEAD || echo "Nothing to revert"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_PB }}
