name: Deploy to Staging on Kubernetes

on:
  workflow_dispatch:
  push:
    branches:
      - Staging-Kubernetes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: agile-tracker-jar

      - name: List downloaded files
        run: ls -R

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run JAR (optional)
        run: java -jar *.jar
        # Replace this with actual deployment if needed
